### ISSUE TITLE
No module named "win32com"

### ISSUE THREAD

**Issue by extremety1989** [sony/nnabla#1025]
i installed framework with(Pdm package manager)  -> " pdm add nnabla-ext-cuda110 " and i got this error

Traceback (most recent call last):
  File "C:\Users\*\Desktop\Space\main.py", line 6, in <module>
    import nnabla as nn
  File "C:\Users\*\Desktop\Space\__pypackages__\3.9\lib\nnabla\__init__.py", line 17, in <module>
    from .logger import logger
  File "C:\Users\*\Desktop\Space\__pypackages__\3.9\lib\nnabla\logger.py", line 70, in <module>
    from .config import nnabla_config
  File "C:\Users\*\Desktop\Space\__pypackages__\3.9\lib\nnabla\config.py", line 92, in <module>
    nnabla_config = _get_nnabla_config()
  File "C:\Users\*\Desktop\Space\__pypackages__\3.9\lib\nnabla\config.py", line 71, in _get_nnabla_config
    from win32com.shell import shell, shellcon
ModuleNotFoundError: No module named 'win32com'

**Comment by TomonobuTsujikawa** [comment]
I think this `win32com` error will disappear after you try `pdm add pywin32` .
Please note that CUDA environment has to be setup correctly if you use nnabla-ext-cuda110.

**Comment by extremety1989** [comment]
solved, thank you
