### ISSUE TITLE
Example DeeplabV3 not works

### ISSUE THREAD

**Issue by Armin234** [sony/nnabla#1043]
Hi,

the example on the site
https://nnabla.readthedocs.io/en/latest/python/api/models/semantic_segmentation.html
didn't work.

I always get the error: AttributeError: 'NoneType' object has no attribute 'shape'

2022-04-02 19:54:02,584 [nnabla][INFO]: Initializing CPU extension...
2022-04-02 19:54:02,956 [nnabla][INFO]: Initializing CUDA extension...
2022-04-02 19:54:02,987 [nnabla][INFO]: Initializing cuDNN extension...
Loading C:\Users\Armin/nnabla_data\nnp_models\semantic_segmentation/DeepLabV3-voc-coco-os-8.nnp.
2022-04-02 19:54:03,093 [nnabla][INFO]: Downloading DeepLabV3-voc-coco-os-8.nnp from https://nnabla.org/pretrained-models/nnp_models/semantic_segmentation/DeepLabV3-voc-coco-os-8.nnp
2022-04-02 19:54:03,093 [nnabla][INFO]: > C:\Users\Armin/nnabla_data\nnp_models\semantic_segmentation/DeepLabV3-voc-coco-os-8.nnp already exists.
2022-04-02 19:54:03,093 [nnabla][INFO]: > If you have any issue when using this file, 
2022-04-02 19:54:03,093 [nnabla][INFO]: > manually remove the file and try download again.
Traceback (most recent call last):
  File "C:/Users/Armin/Desktop/Python/DeepLabv3/main.py", line 21, in <module>
    y = deeplabv3(x)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\models\semantic_segmentation\deeplabv3plus.py", line 138, in __call__
    net = self.nnp.get_network(
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\utils\nnp_graph.py", line 133, in get_network
    return NnpNetwork(self.network_dict[name], batch_size, callback=callback)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\utils\nnp_graph.py", line 45, in __init__
    self.proto_network = proto_network.promote(callback)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\core\graph_def.py", line 1184, in promote
    return self._patch_by_network_pass(callback)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\core\graph_def.py", line 1081, in _patch_by_network_pass
    functions = filter_function_by_callback(functions, callback)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\core\graph_def.py", line 1068, in filter_function_by_callback
    pf = callback._apply_generate_function_by_name(pf)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\utils\nnp_graph.py", line 295, in _apply_generate_function_by_name
    return self._function_callbacks_by_name[f.name](f)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\utils\nnp_graph.py", line 187, in _callback
    return callback(v)
  File "C:\Users\Armin\Desktop\Python\DeepLabv3\venv\lib\site-packages\nnabla\models\semantic_segmentation\deeplabv3plus.py", line 95, in average_pooling_shape
    s = f.inputs[0].variable.shape
AttributeError: 'NoneType' object has no attribute 'shape'

Process finished with exit code 1

**Comment by TomonobuTsujikawa** [comment]
Thank you for pointing it out. Please let us check.

**Comment by TomonobuTsujikawa** [comment]
Now https://github.com/sony/nnabla/pull/1049 was merged, so you can run this model with latest code.
(nnabla v1.27.0 doesn't contain this change, so next nnabla release (v1.28.0?) will be needed if you use official release)

**Comment by TomonobuTsujikawa** [comment]
I think this issue was resolved, so please let me close.
