### ISSUE TITLE
nnabla python on Windows

### ISSUE THREAD

**Issue by ifeelfree** [sony/nnabla#73]
After installing nnabla Python package in Windows, I tried to import nnabla module, but unfortunately the following errors happened:
```
(nnabla) C:\Users\abc>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nnabla
2017-11-21 15:49:26,440 [nnabla][INFO]: Initializing CPU extension...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abc\AppData\Local\conda\conda\envs\nnabla\lib\site-packages\nnabla\__init__.py", line 42, in <module>
    prefer_cached_array(True)
  File "_init.pyx", line 103, in nnabla._init.prefer_cached_array.lambda
  File "_init.pyx", line 103, in nnabla._init.prefer_cached_array.lambda
TypeError: a bytes-like object is required, not 'str'
```
Could you give some clues on how to fix this problem? Thanks

**Comment by TakuyaNarihira** [comment]
Now it should be fixed at 0.9.6.  Thanks
